### ISSUE TITLE
Setting templateFile has no effect

### ISSUE THREAD

**Issue by vigri** [simonschaufi/gkh_rss_import#17]
Hello,

I've installed the extension and tried to specify my own (modified) template file.
However this had no effect.

Taking a look into the code I identified this line to be responsible for detecting whether a custom template (specified by the user via TypoScript) should be used or not:
https://github.com/simonschaufi/gkh_rss_import/blob/89ff60017ed9871ef2b5e730e0e7415d76c4a192/Classes/Controller/RssImportController.php#L141

In my opinion there's never ever a case where a custom path to a `templateFile` is taken into account.

I think the above line should be changed to `if (strpos($templateFile, 'EXT:') === false)`.
If you're okay with that @simonschaufisimonschaufi I can create a PR (if needed).

Best regards

**Comment by simonschaufi** [comment]
I'm actually using this extension in a project and the mentioned line says: if the template file starts with `EXT:` then execute the block. Unfortunately it's not possible to reference a file in like fileadmin or so but it needs to be set either via the plugin settings in the BE or must start with `EXT:`, otherwise it won't work. Since this works correctly, there is nothing that needs to be fixed.
